// eslint-disable-next-line import/order
import type { NextPage } from 'next';
import Head from 'next/head';
import LoginForm from '../components/layouts/LoginForm';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>BaseWallet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <LoginForm />
      </main>
    </div>
  );
};

export default Home;
